<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>999.9.9-dev</Version>
    <Company>855Media</Company>
    <Copyright>Copyright (C) 855Media</Copyright>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
  </ItemGroup>
</Project>
