using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using _855Media.Core.Dubbing;
using _855Media.Core.Utils;
using Gress;
using YoutubeExplode;
using YoutubeExplode.Converter;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;
using YoutubeExplode.Videos.Streams;

namespace _855Media.Core.Downloading;

public class VideoDownloader(IReadOnlyList<Cookie>? initialCookies = null) : IDisposable
{
    private readonly YoutubeClient _youtube = new(Http.Client, initialCookies ?? []);
    private readonly IReadOnlyList<Cookie>? _cookies = initialCookies;

    public async Task<IReadOnlyList<VideoDownloadOption>> GetDownloadOptionsAsync(
        VideoId videoId,
        bool includeLanguageSpecificAudioStreams = true,
        CancellationToken cancellationToken = default
    )
    {
        try
        {
            var manifest = await _youtube.Videos.Streams.GetManifestAsync(
                videoId,
                cancellationToken
            );
            var options = VideoDownloadOption.ResolveAll(
                manifest,
                includeLanguageSpecificAudioStreams
            );
            if (options.Count > 0)
                return options;
        }
        catch
        {
            // Fall back to resolving available formats with yt-dlp if YoutubeExplode manifest parsing fails (HTTP 400 Bad Request / 403)
        }

        var ytUrl = $"https://www.youtube.com/watch?v={videoId}";
        var ytDlpOptions = await YtDlp.ResolveDownloadOptionsAsync(
            ytUrl,
            _cookies,
            cancellationToken
        );
        if (ytDlpOptions.Count > 0)
            return ytDlpOptions;

        return YtDlp.GetDefaultOptions();
    }

    public async Task<VideoDownloadOption> GetBestDownloadOptionAsync(
        VideoId videoId,
        VideoDownloadPreference preference,
        bool includeLanguageSpecificAudioStreams = true,
        CancellationToken cancellationToken = default
    )
    {
        var options = await GetDownloadOptionsAsync(
            videoId,
            includeLanguageSpecificAudioStreams,
            cancellationToken
        );

        return preference.TryGetBestOption(options) ?? YtDlp.GetDefaultOptions().First();
    }

    public async Task DownloadVideoAsync(
        string filePath,
        IVideo video,
        VideoDownloadOption downloadOption,
        bool includeSubtitles = true,
        bool translateCaptionsToEnglish = false,
        string? ffmpegPath = null,
        IProgress<Percentage>? progress = null,
        CancellationToken cancellationToken = default
    )
    {
        var dirPath = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrWhiteSpace(dirPath))
            Directory.CreateDirectory(dirPath);

        string? tempCookieFile = null;
        try
        {
            var (cookiePath, isTemp) = await TryCreateCookieFileAsync(_cookies, cancellationToken);
            if (isTemp)
                tempCookieFile = cookiePath;

            // If fallback option without stream infos or YoutubeExplode fails, use YtDlp
            if (downloadOption.StreamInfos.Count == 0)
            {
                await DownloadWithYtDlpAsync(
                    filePath,
                    video.Id,
                    downloadOption,
                    ffmpegPath,
                    cookiePath,
                    progress,
                    cancellationToken,
                    includeSubtitles,
                    translateCaptionsToEnglish
                );

                if (!downloadOption.Container.IsAudioOnly)
                {
                    await MediaCompatibility.EnsureWindowsCompatibleAsync(
                        filePath,
                        ffmpegPath,
                        cancellationToken
                    );
                }
                return;
            }

            // Include subtitles in the output container
            var trackInfos = new List<ClosedCaptionTrackInfo>();
            ClosedCaptionTrackInfo? englishTrack = null;
            ClosedCaptionManifest? captionManifest = null;

            if (
                (includeSubtitles || translateCaptionsToEnglish)
                && !downloadOption.Container.IsAudioOnly
            )
            {
                try
                {
                    captionManifest = await _youtube.Videos.ClosedCaptions.GetManifestAsync(
                        video.Id,
                        cancellationToken
                    );

                    if (translateCaptionsToEnglish)
                    {
                        // Check if an English track already exists (prefer non-auto-generated first)
                        englishTrack =
                            captionManifest.Tracks.FirstOrDefault(t =>
                                !t.IsAutoGenerated
                                && t.Language.Code.StartsWith(
                                    "en",
                                    StringComparison.OrdinalIgnoreCase
                                )
                            )
                            ?? captionManifest.Tracks.FirstOrDefault(t =>
                                t.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase)
                            );

                        if (englishTrack is null && captionManifest.Tracks.Count > 0)
                        {
                            // Pick best base track to translate from (prefer human-authored track)
                            var baseTrack =
                                captionManifest.Tracks.FirstOrDefault(t => !t.IsAutoGenerated)
                                ?? captionManifest.Tracks.First();

                            var autoEnUrl = baseTrack.Url.Contains('?')
                                ? baseTrack.Url + "&tlang=en"
                                : baseTrack.Url + "?tlang=en";

                            englishTrack = new ClosedCaptionTrackInfo(
                                autoEnUrl,
                                new Language("en", "English"),
                                isAutoGenerated: true
                            );
                        }

                        if (englishTrack is not null)
                        {
                            trackInfos.Add(englishTrack);
                        }
                    }

                    if (includeSubtitles)
                    {
                        foreach (var track in captionManifest.Tracks)
                        {
                            if (
                                !trackInfos.Any(t =>
                                    t.Url == track.Url
                                    || (
                                        t.Language.Code == track.Language.Code
                                        && t.IsAutoGenerated == track.IsAutoGenerated
                                    )
                                )
                            )
                            {
                                trackInfos.Add(track);
                            }
                        }
                    }
                }
                catch
                {
                    // Subtitles missing or unavailable
                }
            }

            try
            {
                await _youtube.Videos.DownloadAsync(
                    downloadOption.StreamInfos,
                    trackInfos,
                    new ConversionRequestBuilder(filePath)
                        .SetFFmpegPath(ffmpegPath ?? FFmpeg.TryGetCliFilePath() ?? "ffmpeg")
                        .SetContainer(downloadOption.Container)
                        .SetPreset(ConversionPreset.Medium)
                        .Build(),
                    progress?.ToDoubleBased(),
                    cancellationToken
                );
            }
            catch
            {
                // Fallback to YtDlp if YoutubeExplode download fails midway
                await DownloadWithYtDlpAsync(
                    filePath,
                    video.Id,
                    downloadOption,
                    ffmpegPath,
                    cookiePath,
                    progress,
                    cancellationToken,
                    includeSubtitles,
                    translateCaptionsToEnglish
                );
            }

            // Save translated English .srt alongside the video if requested
            if (translateCaptionsToEnglish && englishTrack is not null)
            {
                var srtPath = Path.ChangeExtension(filePath, ".srt");
                try
                {
                    await _youtube.Videos.ClosedCaptions.DownloadAsync(
                        englishTrack,
                        srtPath,
                        cancellationToken: cancellationToken
                    );
                }
                catch
                {
                    // Fallback to translating base track via SubtitleTranslationService
                    try
                    {
                        var baseTrack =
                            captionManifest?.Tracks.FirstOrDefault(t => !t.IsAutoGenerated)
                            ?? captionManifest?.Tracks.FirstOrDefault();
                        if (baseTrack is not null)
                        {
                            var tempBaseSrt = Path.Combine(
                                Path.GetTempPath(),
                                $"base_{Guid.NewGuid():N}.srt"
                            );
                            try
                            {
                                await _youtube.Videos.ClosedCaptions.DownloadAsync(
                                    baseTrack,
                                    tempBaseSrt,
                                    cancellationToken: cancellationToken
                                );
                                if (File.Exists(tempBaseSrt))
                                {
                                    var baseContent = await File.ReadAllTextAsync(
                                        tempBaseSrt,
                                        cancellationToken
                                    );
                                    var subService = new SubtitleTranslationService();
                                    var segments = subService.ParseSrt(baseContent);
                                    if (segments.Count > 0)
                                    {
                                        await subService.TranslateSegmentsToEnglishAsync(
                                            segments,
                                            baseTrack.Language.Code,
                                            cancellationToken: cancellationToken
                                        );
                                        var translatedSrt = SubtitleTranslationService.GenerateSrt(
                                            segments,
                                            useEnglishText: true
                                        );
                                        await File.WriteAllTextAsync(
                                            srtPath,
                                            translatedSrt,
                                            new UTF8Encoding(false),
                                            cancellationToken
                                        );
                                    }
                                }
                            }
                            finally
                            {
                                if (File.Exists(tempBaseSrt))
                                {
                                    try
                                    {
                                        File.Delete(tempBaseSrt);
                                    }
                                    catch { }
                                }
                            }
                        }
                    }
                    catch
                    {
                        // Caption file creation is non-critical
                    }
                }
            }

            if (!downloadOption.Container.IsAudioOnly)
            {
                await MediaCompatibility.EnsureWindowsCompatibleAsync(
                    filePath,
                    ffmpegPath,
                    cancellationToken
                );
            }
        }
        finally
        {
            if (!string.IsNullOrWhiteSpace(tempCookieFile) && File.Exists(tempCookieFile))
            {
                try
                {
                    File.Delete(tempCookieFile);
                }
                catch { }
            }
        }
    }

    private static async Task DownloadWithYtDlpAsync(
        string filePath,
        VideoId videoId,
        VideoDownloadOption downloadOption,
        string? ffmpegPath,
        string? cookiePath,
        IProgress<Percentage>? progress,
        CancellationToken cancellationToken,
        bool includeSubtitles = true,
        bool translateCaptionsToEnglish = false
    )
    {
        var arguments = BuildYtDlpArguments(
            filePath,
            videoId,
            downloadOption,
            ffmpegPath,
            cookiePath,
            allowAnyFormat: false,
            includeSubtitles: includeSubtitles,
            translateCaptionsToEnglish: translateCaptionsToEnglish
        );

        try
        {
            await YtDlp.RunAsync(arguments, progress, cancellationToken);
        }
        catch (Exception ex)
        {
            if (!string.IsNullOrWhiteSpace(cookiePath) && IsCookieRelatedError(ex.Message))
            {
                var fallbackArgs = BuildYtDlpArguments(
                    filePath,
                    videoId,
                    downloadOption,
                    ffmpegPath,
                    cookieFilePath: null,
                    allowAnyFormat: false,
                    includeSubtitles: includeSubtitles,
                    translateCaptionsToEnglish: translateCaptionsToEnglish
                );
                try
                {
                    await YtDlp.RunAsync(fallbackArgs, progress, cancellationToken);
                    EnsureYtDlpSrtFile(filePath, translateCaptionsToEnglish);
                    return;
                }
                catch (Exception ex2) when (IsFormatUnavailableError(ex2.Message))
                {
                    var anyFormatArgs = BuildYtDlpArguments(
                        filePath,
                        videoId,
                        downloadOption,
                        ffmpegPath,
                        cookieFilePath: null,
                        allowAnyFormat: true,
                        includeSubtitles: includeSubtitles,
                        translateCaptionsToEnglish: translateCaptionsToEnglish
                    );
                    await YtDlp.RunAsync(anyFormatArgs, progress, cancellationToken);
                    EnsureYtDlpSrtFile(filePath, translateCaptionsToEnglish);
                    return;
                }
            }

            if (IsFormatUnavailableError(ex.Message))
            {
                var anyFormatArgs = BuildYtDlpArguments(
                    filePath,
                    videoId,
                    downloadOption,
                    ffmpegPath,
                    cookiePath,
                    allowAnyFormat: true,
                    includeSubtitles: includeSubtitles,
                    translateCaptionsToEnglish: translateCaptionsToEnglish
                );
                await YtDlp.RunAsync(anyFormatArgs, progress, cancellationToken);
                EnsureYtDlpSrtFile(filePath, translateCaptionsToEnglish);
                return;
            }

            throw;
        }

        EnsureYtDlpSrtFile(filePath, translateCaptionsToEnglish);
    }

    private static void EnsureYtDlpSrtFile(string filePath, bool translateCaptionsToEnglish)
    {
        if (!translateCaptionsToEnglish)
            return;

        var srtPath = Path.ChangeExtension(filePath, ".srt");
        if (File.Exists(srtPath))
            return;

        var enSrt = Path.ChangeExtension(filePath, ".en.srt");
        if (File.Exists(enSrt))
        {
            try
            {
                File.Copy(enSrt, srtPath, overwrite: true);
            }
            catch { }
        }
    }

    private static bool IsFormatUnavailableError(string message) =>
        message.Contains("Requested format is not available", StringComparison.OrdinalIgnoreCase)
        || message.Contains("Only images are available", StringComparison.OrdinalIgnoreCase);

    private static bool IsCookieRelatedError(string message) =>
        message.Contains("cookie", StringComparison.OrdinalIgnoreCase)
        || message.Contains("Netscape", StringComparison.OrdinalIgnoreCase);

    private static Task<(string? Path, bool IsTemp)> TryCreateCookieFileAsync(
        IReadOnlyList<Cookie>? cookies,
        CancellationToken cancellationToken
    ) => YtDlp.TryCreateCookieFileAsync(cookies, cancellationToken);

    internal static IReadOnlyList<string> BuildYtDlpArguments(
        string filePath,
        VideoId videoId,
        VideoDownloadOption downloadOption,
        string? ffmpegPath,
        string? cookieFilePath = null,
        bool allowAnyFormat = false,
        bool includeSubtitles = true,
        bool translateCaptionsToEnglish = false
    )
    {
        var ext = Path.GetExtension(filePath);
        var isAudioOnly =
            downloadOption.Container.IsAudioOnly
            || ext.Equals(".mp3", StringComparison.OrdinalIgnoreCase)
            || ext.Equals(".m4a", StringComparison.OrdinalIgnoreCase)
            || ext.Equals(".opus", StringComparison.OrdinalIgnoreCase)
            || ext.Equals(".wav", StringComparison.OrdinalIgnoreCase);

        var arguments = new List<string> { "--no-playlist", "--force-overwrites", "-o", filePath };

        var ffmpegCliPath = ffmpegPath ?? FFmpeg.TryGetCliFilePath();
        if (!string.IsNullOrWhiteSpace(ffmpegCliPath))
        {
            arguments.Add("--ffmpeg-location");
            arguments.Add(ffmpegCliPath);
        }

        if (!string.IsNullOrWhiteSpace(cookieFilePath) && File.Exists(cookieFilePath))
        {
            arguments.Add("--cookies");
            arguments.Add(cookieFilePath);
        }

        var jsRuntime = TryFindJsRuntime();
        if (!string.IsNullOrWhiteSpace(jsRuntime))
        {
            arguments.Add("--js-runtimes");
            arguments.Add($"node:{jsRuntime}");
        }

        var targetHeight = downloadOption.VideoQuality?.MaxHeight;

        if (isAudioOnly)
        {
            arguments.Add("--format");
            arguments.Add("bestaudio/best");

            if (
                ext.Equals(".mp3", StringComparison.OrdinalIgnoreCase)
                || downloadOption.Container == Container.Mp3
            )
            {
                arguments.Add("--extract-audio");
                arguments.Add("--audio-format");
                arguments.Add("mp3");
            }
            else if (
                ext.Equals(".m4a", StringComparison.OrdinalIgnoreCase)
                || downloadOption.Container.Name.Equals("m4a", StringComparison.OrdinalIgnoreCase)
            )
            {
                arguments.Add("--extract-audio");
                arguments.Add("--audio-format");
                arguments.Add("m4a");
            }
            else if (
                ext.Equals(".wav", StringComparison.OrdinalIgnoreCase)
                || downloadOption.Container.Name.Equals("wav", StringComparison.OrdinalIgnoreCase)
            )
            {
                arguments.Add("--extract-audio");
                arguments.Add("--audio-format");
                arguments.Add("wav");
            }
            else
            {
                arguments.Add("--extract-audio");
            }
        }
        else if (allowAnyFormat)
        {
            arguments.Add("--format");
            if (targetHeight is { } mh and > 0)
            {
                // Support both portrait (aspect_ratio < 1, bounded by width)
                // and landscape (aspect_ratio >= 1, bounded by height)
                arguments.Add(
                    $"bestvideo[aspect_ratio<1][width<={mh}]+bestaudio/"
                        + $"bestvideo[aspect_ratio>=1][height<={mh}]+bestaudio/"
                        + $"bestvideo[height<={mh}]+bestaudio/"
                        + $"bestvideo[width<={mh}]+bestaudio/"
                        + $"bestvideo+bestaudio/best"
                );
            }
            else
            {
                arguments.Add("bestvideo+bestaudio/best");
            }

            arguments.Add("--format-sort");
            if (targetHeight is { } sortHeight and > 0)
            {
                arguments.Add($"res:{sortHeight},fps,quality");
            }
            else
            {
                arguments.Add("res,fps,quality");
            }

            if (
                ext.Equals(".mp4", StringComparison.OrdinalIgnoreCase)
                || downloadOption.Container == YoutubeExplode.Videos.Streams.Container.Mp4
            )
            {
                arguments.Add("--recode-video");
                arguments.Add("mp4");
            }
        }
        else
        {
            arguments.Add("--format");
            if (targetHeight is { } mh and > 0)
            {
                // Support both portrait (aspect_ratio < 1, bounded by width)
                // and landscape (aspect_ratio >= 1, bounded by height)
                arguments.Add(
                    $"bestvideo[aspect_ratio<1][width<={mh}]+bestaudio[acodec^=mp4a]/"
                        + $"bestvideo[aspect_ratio>=1][height<={mh}]+bestaudio[acodec^=mp4a]/"
                        + $"bestvideo[aspect_ratio<1][width<={mh}]+bestaudio[ext=m4a]/"
                        + $"bestvideo[aspect_ratio>=1][height<={mh}]+bestaudio[ext=m4a]/"
                        + $"bestvideo[aspect_ratio<1][width<={mh}]+bestaudio/"
                        + $"bestvideo[aspect_ratio>=1][height<={mh}]+bestaudio/"
                        + $"bestvideo[height<={mh}]+bestaudio/"
                        + $"bestvideo[width<={mh}]+bestaudio/"
                        + $"bestvideo+bestaudio/best"
                );
            }
            else
            {
                arguments.Add(
                    "bestvideo+bestaudio[acodec^=mp4a]/"
                        + "bestvideo+bestaudio[ext=m4a]/"
                        + "bestvideo+bestaudio/best"
                );
            }

            arguments.Add("--format-sort");
            if (targetHeight is { } sortHeight and > 0)
            {
                if (sortHeight >= 1440)
                {
                    // 2K (1440p), 4K (2160p), and 8K (4320p) are exclusively VP9/AV1 on YouTube.
                    // Do not prefer AVC or penalize VP9/AV1, ensuring the requested 4K/2K resolution is preserved.
                    arguments.Add($"res:{sortHeight},fps,quality");
                }
                else
                {
                    // For <= 1080p, prioritize the target resolution first, then prefer AVC (H.264)
                    // and AAC audio for native playback without transcoding.
                    arguments.Add($"res:{sortHeight},fps,vcodec:avc,acodec:m4a");
                }
            }
            else
            {
                arguments.Add("res,fps,vcodec:avc,acodec:m4a");
            }

            if (
                ext.Equals(".mp4", StringComparison.OrdinalIgnoreCase)
                || downloadOption.Container == YoutubeExplode.Videos.Streams.Container.Mp4
            )
            {
                // Re-encode incompatible VP9/AV1/Opus streams to H.264/AAC if necessary
                arguments.Add("--recode-video");
                arguments.Add("mp4");
            }
        }

        if (!isAudioOnly)
        {
            if (translateCaptionsToEnglish)
            {
                arguments.Add("--write-subs");
                arguments.Add("--write-auto-subs");
                arguments.Add("--sub-langs");
                arguments.Add("en.*,en");
                arguments.Add("--embed-subs");
                arguments.Add("--sub-format");
                arguments.Add("srt/best");
            }
            else if (includeSubtitles)
            {
                arguments.Add("--write-subs");
                arguments.Add("--embed-subs");
                arguments.Add("--sub-format");
                arguments.Add("srt/best");
            }
        }

        arguments.Add($"https://www.youtube.com/watch?v={videoId}");

        return arguments;
    }

    private static string? TryFindJsRuntime()
    {
        var candidates = new[]
        {
            @"C:\Program Files\nodejs\node.exe",
            @"C:\Program Files (x86)\nodejs\node.exe",
            Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                "AppData",
                "Roaming",
                "npm",
                "node.exe"
            ),
            Path.Combine(AppContext.BaseDirectory, "node", "node.exe"),
            Path.Combine(AppContext.BaseDirectory, "node.exe"),
        };

        foreach (var path in candidates)
        {
            if (File.Exists(path))
                return path;
        }

        var pathEnv = Environment.GetEnvironmentVariable("PATH");
        if (!string.IsNullOrWhiteSpace(pathEnv))
        {
            foreach (
                var dir in pathEnv.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            )
            {
                var candidate = Path.Combine(dir.Trim(), "node.exe");
                if (File.Exists(candidate))
                    return candidate;
            }
        }

        return null;
    }

    public void Dispose() => _youtube.Dispose();
}
